version: "3.8"

services:
  customer_service:
    image: golang:1.21.4-alpine3.18
    container_name: customer_service
    ports:
      - "50051:6379"
    environment:
      - SERVER_PORT=6379
      - DB_MAX_CONNECTIONS=10
      - DB_MAX_IDLE_CONNECTIONS=60
      - DB_MAX_LIFETIME_CONNECTIONS=120
      - DB_HOST=customer_postgresql
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=customer_db
      - DB_SSL_MODE=disable
    depends_on:
      - customer_postgresql
    restart: always
    working_dir:
      /usr/app
    volumes:
      - ./services/customer:/usr/app
    command:
      go run main.go
    networks:
      - service

  customer_postgresql:
    image: postgres:16.1-alpine3.18
    container_name: customer_postgresql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=customer_db
    volumes:
      - ./services/customer/db:/var/lib/postgresql/data
    networks:
      - service
networks:
  service:
    driver: bridge
