// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: SharedEntities/SharedEntities.proto

package SharedEntities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_RUBLES  Currency = 0
	Currency_DOLLARS Currency = 1
	Currency_EURO    Currency = 2
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "RUBLES",
		1: "DOLLARS",
		2: "EURO",
	}
	Currency_value = map[string]int32{
		"RUBLES":  0,
		"DOLLARS": 1,
		"EURO":    2,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_SharedEntities_SharedEntities_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_SharedEntities_SharedEntities_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_SharedEntities_SharedEntities_proto_rawDescGZIP(), []int{0}
}

var File_SharedEntities_SharedEntities_proto protoreflect.FileDescriptor

var file_SharedEntities_SharedEntities_proto_rawDesc = []byte{
	0x0a, 0x23, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x2f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x2a, 0x2d, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x55, 0x42, 0x4c, 0x45, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x4f, 0x4c, 0x4c, 0x41, 0x52, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x55,
	0x52, 0x4f, 0x10, 0x02, 0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SharedEntities_SharedEntities_proto_rawDescOnce sync.Once
	file_SharedEntities_SharedEntities_proto_rawDescData = file_SharedEntities_SharedEntities_proto_rawDesc
)

func file_SharedEntities_SharedEntities_proto_rawDescGZIP() []byte {
	file_SharedEntities_SharedEntities_proto_rawDescOnce.Do(func() {
		file_SharedEntities_SharedEntities_proto_rawDescData = protoimpl.X.CompressGZIP(file_SharedEntities_SharedEntities_proto_rawDescData)
	})
	return file_SharedEntities_SharedEntities_proto_rawDescData
}

var file_SharedEntities_SharedEntities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SharedEntities_SharedEntities_proto_goTypes = []interface{}{
	(Currency)(0), // 0: sharedEntities.Currency
}
var file_SharedEntities_SharedEntities_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SharedEntities_SharedEntities_proto_init() }
func file_SharedEntities_SharedEntities_proto_init() {
	if File_SharedEntities_SharedEntities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SharedEntities_SharedEntities_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SharedEntities_SharedEntities_proto_goTypes,
		DependencyIndexes: file_SharedEntities_SharedEntities_proto_depIdxs,
		EnumInfos:         file_SharedEntities_SharedEntities_proto_enumTypes,
	}.Build()
	File_SharedEntities_SharedEntities_proto = out.File
	file_SharedEntities_SharedEntities_proto_rawDesc = nil
	file_SharedEntities_SharedEntities_proto_goTypes = nil
	file_SharedEntities_SharedEntities_proto_depIdxs = nil
}
